# -*- coding: utf-8 -*-
"""Seaborn .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FS2CsSdq_OD4rc5SIV7LrlRAoY73ffmO
"""

# import required lib
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# import the inbuild datasets

# tips datasets
tips = sns.load_dataset("tips")

#iris Datasets
iris =  sns.load_dataset("iris")

#titanic
titanic  = sns.load_dataset('titanic')

# penguins
penguins = sns.load_dataset('penguins')

# flights
flights  = sns.load_dataset('flights')
tips

#set theme
sns.set_theme(style='whitegrid',
              palette='dark',
              font_scale=1.1)

"""#  PART 1 — catplot() Function"""

# catplot() can create ALL these plot types:
# 'strip', 'swarm', 'box', 'violin',
# 'point', 'bar', 'count', 'boxen'



# make the simple catplot

sns.catplot(data = tips,
           x = "day",
           y = "total_bill",
           hue = "size",
           kind = "swarm",
          )

# make the all plots


# Create 2x4 grid
fig, axes = plt.subplots(2, 4, figsize=(20, 10))

# title of figure
fig.suptitle("Categorical Plots - All 8 Types",
             fontsize=18,
             fontweight="bold")

axes = axes.flatten()

# 1. Strip Plot
sns.stripplot(
    data=tips,
    x="day",
    y="total_bill",
    hue="sex",
    palette="deep",
    ax=axes[0]
)
axes[0].set_title("strip")

# 2. Swarm Plot
sns.swarmplot(
    data=tips,
    x="day",
    y="total_bill",
    hue="sex",
    palette="deep",
    ax=axes[1]
)
axes[1].set_title("swarm")

# 3. Box Plot
sns.boxplot(
    data=tips,
    x="day",
    y="total_bill",
    hue="sex",
    palette="deep",
    ax=axes[2]
)
axes[2].set_title("box")

# 4. Violin Plot
sns.violinplot(
    data=tips,
    x="day",
    y="total_bill",
    hue="sex",
    palette="deep",
    ax=axes[3]
)
axes[3].set_title("violin")

# 5. Boxen Plot
sns.boxenplot(
    data=tips,
    x="day",
    y="total_bill",
    hue="sex",
    palette="deep",
    ax=axes[4]
)
axes[4].set_title("boxen")

# 6. Point Plot
sns.pointplot(
    data=tips,
    x="day",
    y="total_bill",
    hue="sex",
    palette="deep",
    ax=axes[5]
)
axes[5].set_title("point")

# 7. Bar Plot
sns.barplot(
    data=tips,
    x="day",
    y="total_bill",
    hue="sex",
    palette="deep",
    ax=axes[6]
)
axes[6].set_title("bar")

# 8. Count Plot
sns.countplot(
    data=tips,
    x="day",
    hue="sex",
    palette="deep",
    ax=axes[7]
)
axes[7].set_title("count")

plt.tight_layout()
plt.show()

# make the simple catplot

sns.catplot(data = tips,
           x = "day",
           y = "total_bill",
           hue = "size",
           col = "time",
           palette=['red', 'blue'],
           height=5,
           aspect=0.9,
           linewidth=1.5 ,
           kind = "swarm",
          )

10 % 2

int(5.0 % 2)

int(2.5 % 2)

int(1.25 % 2 )

1.25 / 2

def binary(n):
    if n == 0:
        return "0"

    result = ""

    while n > 0:
        result += str(n & 1)  # get rightmost bit
        n = n >> 1            # shift right

    return result[::-1]       # reverse


print(binary(13))

def binary(n):
    result = ""

    while n > 0:
        result = str(n % 2) + result
        n = n // 2

    return result

print(binary(13))

